### ISSUE TITLE
Please create nice docker-compose file

### ISSUE THREAD

**Issue by murmelbahn** [Cesura/pastey#11]
Hi,
your project is really interesting but I think its not cool to clone the whole github repo to let it run with docker-compose.
Can you please provide a docker-compose file which is able to run "standalone"?

Thank you!

**Comment by Cesura** [comment]
I'm not sure what you mean by "nice"? You can already do this:
`$ wget https://raw.githubusercontent.com/Cesura/pastey/main/docker-compose.yml`
`$ docker-compose up -d`

**Comment by Cesura** [comment]
Updated the README to make it more clear to all:
https://github.com/Cesura/pastey/commit/7b705b5a47483db92bd0b8d0f09b98ace8264fb7
