### ISSUE TITLE
Yaml mistaken for Markdown

### ISSUE THREAD

**Issue by mkono87** [Cesura/pastey#14]
As the title states pastey keeps thinking my yaml is markdown. Is there something I can put to make it detect it properly?

**Comment by WolfwithSword** [comment]
I think this may be because of the current version of guesslang in the requirements.txt. Currently it's set to version 2.0.1, while 2.2.1 is the latest. I'm not sure when they added YAML support (among several other languages), but it's not available in v2.0.1, but is in v2.2.1.
