### ISSUE TITLE
docker-compose.yml?

### ISSUE THREAD

**Issue by aazam476** [Cesura/pastey#2]
Will there be a docker-compose.yml?

**Comment by Cesura** [comment]
As it's just a single container rather than a collection of services, I did not think it would be important to include a docker-compose file. However, if this would be useful, let me know and I can include it.

**Comment by Cesura** [comment]
Fixed in:
https://github.com/Cesura/pastey/commit/074c16f3a013a0b436701d7113191da6b6766eaf
