### ISSUE TITLE
Raw text view

### ISSUE THREAD

**Issue by Leopere** [Cesura/pastey#20]
With Hastebin and other various paste services you can curl from a URL directly or view text in raw rather than having to manually remove line ID numbers when you copy stuff out.

**Comment by Cesura** [comment]
Hi, this feature has been added in version 0.5.

You can access the raw text view with the following URL pattern (link available on paste page): **/view/\<paste-id\>/raw**

**Comment by Leopere** [comment]
Hell yeah thanks heaps!
