### ISSUE TITLE
Password Protection

### ISSUE THREAD

**Issue by aazam476** [Cesura/pastey#3]
Is there anyway to include Password Protection?

**Comment by Cesura** [comment]
Right now, if you choose "Encrypt", the key functions as sort of a password protection:
`http://example.com/view/{paste id}/{decryption key}`

Without the last part of the URL, the paste will not be viewable. Of course, for this to be secure, the site should be using HTTPS (and also it could persist in the browser history).

I can consider adding this feature in the future though, if there is interest.

**Comment by aazam476** [comment]
I would like password protection because if I make this accessible though a domain, other (unauthorized) people can't create a paste.

**Comment by mkono87** [comment]
> 
> 
> I would like password protection because if I make this accessible though a domain, other (unauthorized) people can't create a paste.

This....Im not sure how whitelisting works in this case.

**Comment by aazam476** [comment]
> > I would like password protection because if I make this accessible though a domain, other (unauthorized) people can't create a paste.
> 
> This....Im not sure how whitelisting works in this case.

It would only allow people with a user to create notes. However, I do believe the creator of every note should be able to choose whether or not a note they created is available to everyone or only people with an account. Also, I believe there should not be any "create account" button, as that would destroy the purpose. Only admins should be able to create new users.
