### ISSUE TITLE
Template hides menu bar when browser is scaled small and vertically

### ISSUE THREAD

**Issue by srgvg** [Cesura/pastey#8]
Noticed it on my smartphone, and confirmed when resizing browser on desktop:

![20210416090722](https://user-images.githubusercontent.com/382239/114985618-4c27f400-9e93-11eb-8c62-ed2635634af1.png)

**Comment by Cesura** [comment]
Fixed in https://github.com/Cesura/pastey/releases/tag/0.4

Thanks!
